### Global Setup Cell

This cell initializes all necessary imports and variables to ensure the notebook runs smoothly from top to bottom, addressing `NameError`s caused by out-of-order execution in the original structure.

In [149]:
import numpy as np

# Definitions for a, b, c, d
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# Definition for arr
arr = np.array([1, 2, 3])

# Definitions for l1, l2, l3, l4
l1 = [10,20,30]
l2 = [40,50,60]
l3 = np.array(l1)
l4 = np.array(l2)

# Definition for x
x = np.arange(1, 17)

# Definition for y (derived from x as per later cell NDRDRGkUYulE)
y = x.reshape(2, 2, -1)

# Definition for a_even
a_even = np.arange(2, 18, 2)

# Definition for arr_1d
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Definition for a_2d
a_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Definition for x1
x1 = np.array([1, 2, 3, 4, 5])

# <center> Numpy Basics </center>

In [150]:
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of c:", c.shape)
print("Shape of d:", d.shape)

Shape of a: ()
Shape of b: (3,)
Shape of c: (2, 3)
Shape of d: (2, 2, 3)


In [151]:
import numpy as np # Redundant: numpy is imported in the global setup cell.

We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [152]:
arr = np.array([1, 2, 3]) # Redundant: 'arr' is defined in the global setup cell.

In [153]:
print(arr)

[1 2 3]


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [154]:
# a = np.array(10) # Redundant: 'a', 'b', 'c', 'd' are defined in the global setup cell.
# b = np.array([1,2,3])
# c = np.array([[1, 2, 3], [4, 5, 6]])
# d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [155]:
print("Dimension of a:", a.ndim)
print("Dimension of b:", b.ndim)
print("Dimension of c:", c.ndim)
print("Dimension of d:", d.ndim)

Dimension of a: 0
Dimension of b: 1
Dimension of c: 2
Dimension of d: 3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [156]:
# print shape of each a,b ,c and d


print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of c:", c.shape)
print("Shape of d:", d.shape)



Shape of a: ()
Shape of b: (3,)
Shape of c: (2, 3)
Shape of d: (2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [157]:
print("Data type of c:", c.dtype)
print("Data type of d:", d.dtype)

Data type of c: int64
Data type of d: int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [158]:
print("Type of a:", type(a))
print("Type of b:", type(b))

Type of a: <class 'numpy.ndarray'>
Type of b: <class 'numpy.ndarray'>


In [159]:
len_b = len(b)
print("Length of b:", len_b)

Length of b: 3


Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [160]:
# l1 = [10,20,30] # Redundant: 'l1', 'l2', 'l3', 'l4' are defined in the global setup cell.
# l2 = [40,50,60]
# l3 = np.array(l1)
# l4 = np.array(l2)

Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [161]:
%%timeit
result_list = [l1[i] * l2[i] for i in range(len(l1))]

205 ns ± 21.8 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [162]:
%%timeit
result_array = l3 * l4

474 ns ± 5.99 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [163]:
arr_arange = np.arange(1, 11)
print(arr_arange)

[ 1  2  3  4  5  6  7  8  9 10]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [164]:
arr_arange_step = np.arange(1, 11, 2)
print(arr_arange_step)

[1 3 5 7 9]


In [165]:
arr_eye = np.eye(3)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [166]:
# x = np.arange(1, 17) # Redundant: 'x' is defined in the global setup cell.

In [167]:
x_reshaped_2d = x.reshape(2, 8)
print(x_reshaped_2d)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [168]:
x_reshaped_3d = x.reshape(2, 4, 2)
print(x_reshaped_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [169]:
x_unknown_dim = x.reshape(4, -1)
print(x_unknown_dim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [170]:
# y = x.reshape(2, 2, -1) # Redundant: 'y' is defined in the global setup cell.

In [171]:
y_flattened = y.reshape(-1)
print(y_flattened)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [172]:
# a_even = np.arange(2, 18, 2) # Redundant: 'a_even' is defined in the global setup cell.

In [173]:
third_element = a_even[2]
print("Third element:", third_element)

Third element: 6


In [174]:
selected_elements = a_even[[2, 4, 6]]
print("3rd, 5th, and 7th elements:", selected_elements)

3rd, 5th, and 7th elements: [ 6 10 14]


Lets check the same for 2 D array

In [175]:
# a_2d = np.array([[1,2,3],[4,5,6],[7,8,9]]) # Redundant: 'a_2d' is defined in the global setup cell.

In [176]:
element = a_2d[2, 2]
print("3rd element from the 3rd row:", element)

3rd element from the 3rd row: 9


Well done!

Now lets check indexing for 3 D array

In [177]:
b_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [178]:
element_3d = b_3d[0, 1, 2]
print("3rd element from 2nd list within 1st nested list:", element_3d)

3rd element from 2nd list within 1st nested list: 6


In [179]:
# arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) # Redundant: 'arr_1d' is defined in the global setup cell.

In [180]:
sliced_arr_1_5 = arr_1d[1:5]
print(sliced_arr_1_5)

[2 3 4 5]


Note: The result includes the start index, but excludes the end index.



In [181]:
sliced_arr_5_end = arr_1d[5:]
print(sliced_arr_5_end)

[ 6  7  8  9 10]


In [182]:
sliced_arr_beg_5 = arr_1d[:5]
print(sliced_arr_beg_5)

[1 2 3 4 5]


**STEP**

Use the step value to determine the step of the slicing:

In [183]:
sliced_arr_step = arr_1d[1:8:2]
print(sliced_arr_step)

[2 4 6 8]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [184]:
sliced_arr_all_step = arr_1d[::2]
print(sliced_arr_all_step)

[1 3 5 7 9]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [185]:
print(a_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [186]:
sliced_2d_row_col = a_2d[2, 1:5]
print(sliced_2d_row_col)

[8 9]


In [187]:
sliced_2d_all_rows_col2 = a_2d[:, 2]
print(sliced_2d_all_rows_col2)

[3 6 9]


In [188]:
sliced_2d_all_rows_col_1_end = a_2d[:, 1:]
print(sliced_2d_all_rows_col_1_end)

[[2 3]
 [5 6]
 [8 9]]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [189]:
x1 = np.array([1, 2, 3, 4, 5]) # Redundant: 'x1' is defined in the global setup cell.

In [190]:
x2 = x1

In [191]:
print("x1:", x1)
print("x2:", x2)

x1: [1 2 3 4 5]
x2: [1 2 3 4 5]


Ok now you have seen that both of them are same

In [192]:
x2[0] = 10

In [193]:
print("x1 after changing x2:", x1)
print("x2 after changing x2:", x2)

x1 after changing x2: [10  2  3  4  5]
x2 after changing x2: [10  2  3  4  5]


In [194]:
print("x1 and x2 share memory:", x1.base is x2.base)

x1 and x2 share memory: True


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [195]:
x3 = x1.view()

In [196]:
print("x1 and x3 share memory:", x1.base is x3.base)

x1 and x3 share memory: False


Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [197]:
x3[0] = 100

In [198]:
print("x1 after changing x3:", x1)
print("x3 after changing x3:", x3)

x1 after changing x3: [100   2   3   4   5]
x3 after changing x3: [100   2   3   4   5]


Now its proved.

Lets see how **Copy()** function works

In [199]:
x4 = x1.copy()

In [200]:
x4[-1] = 900

In [201]:
print("x1 after changing x4:", x1)
print("x4 after changing x4:", x4)

x1 after changing x4: [100   2   3   4   5]
x4 after changing x4: [100   2   3   4 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [202]:
print("x1 and x4 share memory:", x1.base is x4.base)

x1 and x4 share memory: True


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [203]:
stacked_h = np.hstack((x1, x4))
print(stacked_h)

[100   2   3   4   5 100   2   3   4 900]


In [204]:
stacked_v = np.vstack((x1, x4))
print(stacked_v)

[[100   2   3   4   5]
 [100   2   3   4 900]]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [205]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

concatenated_rows = np.concatenate((arr1, arr2), axis=0)
print("Concatenated along rows:\n", concatenated_rows)

Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [206]:
concatenated_cols = np.concatenate((arr1, arr2), axis=1)
print("Concatenated along columns:\n", concatenated_cols)

Concatenated along columns:
 [[1 2 5 6]
 [3 4 7 8]]


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [207]:
appended_array = np.append(arr1, arr2)
print(appended_array)

[1 2 3 4 5 6 7 8]


Lets use insert() function which Inserts values into array before specified index value

In [208]:
inserted_array = np.insert(x1, 4, x4)
print(inserted_array)

[100   2   3   4 100   2   3   4 900   5]


You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [209]:
deleted_array = np.delete(x2, 1)
print(deleted_array)

[100   3   4   5]


Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!